name: Precommit - Integration Tests
on:
  pull_request_target:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'PROJECT'
      - 'LICENSE'
      - 'mesh-worker-service/README.md'
      - 'tools/README.md'
permissions: read-all
jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    timeout-minutes: 80
    strategy:
      matrix:
        case:
          - name: integration test
            e2e: ".ci/tests/integration/e2e.yaml"
            kind_config: "../kind.yaml"
          - name: integration test with tls
            e2e: ".ci/tests/integration/e2e_with_tls.yaml"
            kind_config: "../kind.yaml"
          - name: integration test with oauth2
            e2e: ".ci/tests/integration-oauth2/e2e.yaml"
            kind_config: "../kind.yaml"
          - name: integration test with downloader
            e2e: ".ci/tests/integration-oauth2/e2e_with_downloader.yaml"
            kind_config: "../kind.yaml"
          - name: integration test on k8s 1.22
            e2e: ".ci/tests/integration/e2e.yaml"
            kind_config: "../kind-122.yaml"
    steps:
      - name: clean disk
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set the e2e kind config file
        id: e2e-kind-config
        run: |
          echo "KIND_CONFIG_FILE=${{matrix.case.kind_config}}" >> "$GITHUB_ENV"

      - uses: apache/skywalking-infra-e2e@v1.2.0
        with:
          e2e-file: ${{matrix.case.e2e}}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: failure()

      - name: Cleanup
        if: ${{ failure() }}
        run: e2e cleanup -c ${{matrix.case.e2e}}
